# Arrays



In [13]:
import numpy as np

def arrays(arr):
    n=np.array(arr[::-1],float)
    return n
arr = input().strip().split(' ')
final=arrays(arr)
print(final)

3 4 5 6
[6. 5. 4. 3.]


# Shape and Reshape



In [15]:
import numpy as np

def arrays(arr):
    n=np.array(arr)
    return np.reshape(n,(3,3))


l=list(map(int,input("enter 9 numbers").split()))

final=arrays(l)
print(final)

enter 9 numbers1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten



In [23]:
n,m=map(int,input("enter rows and columns:").split())
print(n,m)
l=[]

for i in range(0,n):
    a=list(map(int,input().split()))
    
    l.append(a)
arr=np.array(l)   
print(np.transpose(arr))
print(arr.flatten())
    
    

enter rows and columns:2 2
2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Concatenate

In [1]:
import numpy as np
n,m,p=map(int,input("enter rows and columns:").split())
print(n,m,p)

l=[]
l1=[]

for i in range(0,n):
    a=list(map(int,input().split()))
    l.append(a)
    
for i in range(0,m):
    b=list(map(int,input().split()))
    l1.append(b)   
    
a1=np.array(l)
a2=np.array(l1)
a3=np.concatenate((a1,a2),axis=0) 
    

enter rows and columns:4 3 2
4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4


# Zeros and Ones

In [3]:
import numpy as np
l=list(map(int,input().split()))
print(np.zeros(l,np.int))
print(np.ones(l,np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Eye and Identity

In [10]:
import numpy as np
n,m=map(int,input("enter rows and columns:").split())
np.set_printoptions(legacy='1.13')
print(np.eye(n,m, k = 0))

enter rows and columns:3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Array Mathematics



In [11]:
import numpy as np
n,m=map(int,input("enter rows and columns:").split())

l=[]

for i in range(0,n):
    a=list(map(int,input().split()))
    
    l.append(a)
arr=np.array(l) 

l1=[]

for i in range(0,m):
    a=list(map(int,input().split()))
    
    l1.append(a)
arr1=np.array(l1) 

print(np.add(arr,arr1),np.subtract(arr,arr1),np.multiply(arr,arr1),np.divide(arr,arr1),np.mod(arr,arr1),np.power(arr,arr1),sep='\n')

enter rows and columns:1 4
1 2 3 4
5 6 7 8
12 2 3 4 
2 55 6 7
2 3 4 5
[[ 6  8 10 12]
 [13  4  6  8]
 [ 3 57  9 11]
 [ 3  5  7  9]]
[[ -4  -4  -4  -4]
 [-11   0   0   0]
 [ -1 -53  -3  -3]
 [ -1  -1  -1  -1]]
[[  5  12  21  32]
 [ 12   4   9  16]
 [  2 110  18  28]
 [  2   6  12  20]]
[[ 0.2         0.33333333  0.42857143  0.5       ]
 [ 0.08333333  1.          1.          1.        ]
 [ 0.5         0.03636364  0.5         0.57142857]
 [ 0.5         0.66666667  0.75        0.8       ]]
[[1 2 3 4]
 [1 0 0 0]
 [1 2 3 4]
 [1 2 3 4]]
[[    1    64  2187 65536]
 [    1     4    27   256]
 [    1     0   729 16384]
 [    1     8    81  1024]]


# Floor, Ceil and Rint

In [1]:
import numpy as np
np.set_printoptions(legacy='1.13')
l=list(map(float,input("enter the numbers").split()))

m=np.array(l)

print(np.floor(m))
print(np.ceil(m))
print(np.rint(m))



enter the numbers2.2 3.3 4.5 1.2 4.8 7.5
[ 2.  3.  4.  1.  4.  7.]
[ 3.  4.  5.  2.  5.  8.]
[ 2.  3.  4.  1.  5.  8.]


# Sum and Prod

In [2]:
import numpy as np
n,m=map(int,input("enter rows and columns:").split())

l=[]

for i in range(0,n):
    a=list(map(int,input().split()))
    
    l.append(a)
arr=np.array(l) 

s=np.sum(arr, axis = 0) 

print(s)

print(np.product(s))

enter rows and columns:2 2
1 2
3 4
[4 6]
24


# Min and Max

In [3]:
import numpy as np
n,m=map(int,input("enter rows and columns:").split())

l=[]

for i in range(0,n):
    a=list(map(int,input().split()))
    
    l.append(a)
arr=np.array(l) 

m=np.min(arr,axis=1)
#print(m)

print(np.max(m))

enter rows and columns:4 2
2 5
3 7
1 3
4 0
[2 3 1 0]
3


# Mean, Var, and Std



In [4]:
import numpy as np
n,m=map(int,input("enter rows and columns:").split())

l=[]

for i in range(0,n):
    a=list(map(int,input().split()))
    
    l.append(a)
arr=np.array(l) 

print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
print(np.std(arr,axis=None))

enter rows and columns:2 2
1 2 
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


# Dot and Cross



In [9]:
import numpy as np
n,m=map(int,input("enter rows and columns:").split())

l=[]

for i in range(0,n):
    a=list(map(int,input().split()))
    
    l.append(a)
arr=np.array(l) 

l1=[]

for i in range(0,m):
    a=list(map(int,input().split()))
    
    l1.append(a)
arr1=np.array(l1) 


print (np.dot(arr,arr1))

enter rows and columns:2 2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# inner and outer

In [10]:
import numpy as np
n,m=map(int,input("enter rows and columns:").split())

l=[]

for i in range(0,n):
    a=list(map(int,input().split()))
    
    l.append(a)
arr=np.array(l) 

l1=[]

for i in range(0,m):
    a=list(map(int,input().split()))
    
    l1.append(a)
arr1=np.array(l1) 


print (np.inner(arr,arr1))

print (np.outer(arr,arr1))

enter rows and columns:1 2
0 1
2 3
1 2
[[3 2]]
[[0 0 0 0]
 [2 3 1 2]]


# Polynomials

In [11]:
import numpy as np
arr=np.array(input().split(),dtype=float)
print(np.polyval(arr,int(input())))

1.1 2 3
0
3.0


# Linear Algebra